repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
  -   id: check-yaml
  -   id: end-of-file-fixer
  -   id: trailing-whitespace
- repo: https://github.com/pycqa/isort
  rev: 5.12.0
  hooks:
    - id: isort
      args: ["--profile", "black"]
- repo: https://github.com/python/black.git
  rev: 22.12.0
  hooks:
    - id: black
      language_version: python3
