includes:
  - configs/semantic/transform.yaml
global:
  exp_name: null
  exist_ok: false
  debug: True
  save_dir: runs
  device: cuda:0
  weights: null
model:
  name: BaseSegModel
  args:
    model_name: unetplusplus
    encoder_name: efficientnet-b0
data:
  dataset:
    name: ImageDataset
    args:
      image_dir: samples/carvana-masking/test_images
      txt_classnames: samples/carvana-masking/classnames.txt
  dataloader:
    name: DataLoaderWithCollator
    args:
      batch_size: 64
      drop_last: True
      shuffle: True
