global:
  exp_name: null
  exist_ok: false
  debug: False
  save_dir: runs
  pretrained: null
  resume: null
  device: cpu
trainer:
  name: MLTrainer
  args:
callbacks:
  - name: SKLearnCheckpointCallbacks
  - name: ShapValueExplainer
    args:
      plot_type: bar
      check_additivity: False
  # - name: PermutationImportance
  - name: TensorboardCallbacks
metrics:
  - name: SKLAccuracy
  - name: SKLBalancedAccuracyMetric
  - name: SKLF1ScoreMetric
  - name: SKLPrecisionRecall
  - name: SKLEmbeddingProjection
