includes:
  - configs/tabular/base/globals.yaml
  - configs/tabular/base/data.yaml
  - configs/tabular/base/transform.yaml
model:
  name: GBClassifiers
  args:
      model_name: lightgbm
      model_config:
        objective: multiclass
        lambda_l1: 0.001
        lambda_l2: 0.001
        num_leaves: 128
        feature_fraction: 0.1
        bagging_fraction: 0.1
        bagging_freq: 7
        min_child_samples: 50
        learning_rate: 0.01
