includes:
  - configs/tabular/base/globals.yaml
  - configs/tabular/base/data.yaml
  - configs/tabular/base/transform.yaml
model:
  name: GBClassifiers
  args:
      model_name: xgboost
      model_config:
        n_estimators: 500 #The number of sequential trees to be modeled
        max_depth: 7 # The maximum depth of a tree.higher depth will allow model to learn relations very specific to a particular sample. Should be tuned
        learning_rate: 0.1 # impact of each tree on the final outcome
        gamma: 0.1 #This will anyways be tuned later.
        reg_alpha: 0 #This will anyways be tuned later.
        reg_lambda: 1 #This will anyways be tuned later.
        early_stopping_rounds: 30
        eval_metric: ['auc']
        objective: "multi:softprob"
