global:
  exp_name: null
  exist_ok: false
  debug: false
  save_dir: runs
  device: cuda:0
  pretrained: null
  resume: null
trainer:
  name: SupervisedTrainer
  args:
    num_iterations: 10000
    clip_grad: 1.0
    evaluate_interval: 1
    use_fp16: true
