includes:
  - configs/base/globals.yaml
  - configs/base/optimizer.yaml
  - configs/detection/transform.yaml

callbacks:
  - name: TorchCheckpointCallbacks
  - name: DetectionVisualizerCallbacks
  - name: TensorboardCallbacks
model:
  name: DETRConvnext
  args:
    model_name: detr
    backbone_name: resnet50
    num_queries: 100
    min_conf: 0.25
    hidden_dim: 256
    position_embedding: sine
    freeze_backbone: false
    dilation: false
    dropout: 0.1
    nheads: 8
    dim_feedforward: 2048
    enc_layers: 6
    dec_layers: 6
    pre_norm: false
    aux_loss: true
loss:
  name: DETRLosses
  args:
    loss_ce: 1
    loss_bbox: 5
    loss_giou: 2
    loss_mask: null
    loss_dice: null
    cost_class: 1
    cost_bbox: 5
    cost_giou: 2
    eos_coef: 0.1
metrics:
  - name: DetectionPrecisionRecall
    args:
       min_conf: 0.2
       min_iou: 0.5
       eps: 1e-6
data:
  dataset:
    train:
      name: COCODataset
      args:
        image_dir: ./data/coco/train2017
        label_path: ./data/coco/annotations/instances_train2017.json
    val:
      name: COCODataset
      args:
        image_dir: ./data/coco/val2017
        label_path: ./data/coco/annotations/instances_val2017.json
  dataloader:
    train:
      name: DataLoaderWithCollator
      args:
        batch_size: 2
        drop_last: true
        shuffle: true
    val:
      name: DataLoaderWithCollator
      args:
        batch_size: 2
        drop_last: false
        shuffle: false
