includes:
  - configs/base/globals.yaml
  - configs/base/optimizer.yaml
  - configs/classification/transform.yaml

callbacks:
  - name: TorchCheckpointCallbacks
    args:
      best_key: bl_acc
  - name: ClassificationVisualizerCallbacks
  - name: TensorboardCallbacks
model:
  name: BaseTimmModel
  args:
    model_name: efficientnet_b0
    from_pretrained: true
loss:
  name: ClassificationCELoss
metrics:
  - name: Accuracy
  - name: BalancedAccuracyMetric
  - name: F1ScoreMetric
    args:
      average: weighted
  - name: ConfusionMatrix
  - name: ErrorCases
data:
  dataset:
    train:
      name: ClassificationImageFolderDataset
      args:
        image_dir: samples/dog-vs-cats/train
        txt_classnames: samples/dog-vs-cats/classnames.txt
    val:
      name: ClassificationImageFolderDataset
      args:
        image_dir: samples/dog-vs-cats/val
        txt_classnames: samples/dog-vs-cats/classnames.txt
  dataloader:
    train:
      name: DataLoaderWithCollator
      args:
        batch_size: 16
        drop_last: false
        shuffle: false
        collate_fn:
          name: MixupCutmixCollator
          args:
            mixup_alpha: 0.4
            cutmix_alpha: 1.0
            weight: [0.2, 0.2]
        sampler:
          name: BalanceSampler
          args:
    val:
      name: DataLoaderWithCollator
      args:
        batch_size: 16
        drop_last: false
        shuffle: true
