includes:
  - configs/classification/transform.yaml
global:
  exp_name: null
  exist_ok: false
  debug: True
  save_dir: runs
  device: cuda:0
  weights: null
model:
  name: BaseTimmModel
  args:
    model_name: efficientnet_b0
    from_pretrained: False
data:
  dataset:
    name: ImageDataset
    args:
      image_dir: samples/dog-vs-cats/test
      txt_classnames: samples/dog-vs-cats/classnames.txt
  dataloader:
    name: DataLoaderWithCollator
    args:
      batch_size: 64
      drop_last: True
      shuffle: True
